### ISSUE TITLE
Use client credentials when talking to CloudFoundry

### ISSUE THREAD

**Issue by AP-Hunt** [hashicorp/vault-plugin-auth-cf#34]
Hi team,

We (GOV.UK PaaS, https://cloud.service.gov.uk) are a team running a CloudFoundry platform. We're looking at using Vault to provide our tenants with a platform-wide secret store, and in particular this plugin to allow deployed apps to access it. 

At the moment, this plugin [uses standard user credentials](https://github.com/hashicorp/vault-plugin-auth-cf/blob/master/util/util.go#L19) when talking to CloudFoundry. This could work for us, but our preference would be to use client credentials. 

Vault will be a part of the platform infrastructure, not the tenants', so it makes more sense for us to have Vault and CloudFoundry's communication be configured as part of our regular deployment process (Bosh), rather than as a task after the rest of CloudFoundry has been deployed.

Would you be open to a PR that:
1. Adds a configuration option to set the credential type
2. Updates [the relevant code path](https://github.com/hashicorp/vault-plugin-auth-cf/blob/master/util/util.go#L19) to switch based on that configuration option.

Regards,
Andy

**Comment by jasonodonnell** [comment]
Hi @AP-Hunt, supporting client credentials makes sense.  We would be happy to review any changes to add this feature.  Let us know if this is how you want to move forward or we can plan to add it.

**Comment by AP-Hunt** [comment]
See my comment on #35

**Comment by barsutka** [comment]
Hi team,
I work for GOV.UK PaaS team, as agreed above, we have created the change needed for client credentials authentication for this plugin.
Here is the [PR](https://github.com/hashicorp/vault-plugin-auth-cf/pull/37) - if you have any questions, feedback or concern - I'll be happy to address those.
Thanks,
Maxim.

**Comment by barsutka** [comment]
Hi team,
The [PR](https://github.com/hashicorp/vault-plugin-auth-cf/pull/37) has been merged, thank you for quick turnaround.

qq - when should we expect this feature to be released? Is there anything that we can monitor (e.g.: Release notes) to get a notification that it has been released?
Thanks in advance,
Maxim.

@jasonodonnell ^^^

**Comment by barsutka** [comment]
Hi team,

Any news on the above?

thanks,
Maxim.

**Comment by kalafut** [comment]
Hi @barsutka. Feature enhancements will be in the next Vault release (1.7). 1.6 just recently came out. You can always use this plugin externally now and then switch to the bundled version in 1.7.

**Comment by barsutka** [comment]
Hi @kalafut  , thanks for the clarification!

**Comment by AP-Hunt** [comment]
@kalafut Do you have any idea when we'll see 1.7 get released? Is there a cutoff point for features making it in to the release? As you can say, we can definitely run custom plugins in the intervening time, but we'd like to switch back to a vanilla release as soon as one with the features we need is available.

**Comment by jasonodonnell** [comment]
Vault major releases are quarterly, so sometime between March and April seems likely. This is not a commitment, however, because a lot of factors go into when Vault releases.

Merged, closing!

**Comment by AP-Hunt** [comment]
@jasonodonnell That's really helpful for us, thanks very much for getting all these PRs reviewed and merged. We'll deploy a custom version for the time being, and switch back to upstream in 1.7 😄

**Comment by markpeterbuckley** [comment]
Hi @jasonodonnell thanks for the messages above. Was wondering if there's been any commitment for the 1.7 release date yet? Cheers

**Comment by markpeterbuckley** [comment]
Hi @jasonodonnell any update on the 1.7 release date as above? 🙃  thanks

**Comment by jasonodonnell** [comment]
@markpeterbuckley I can't give you an exact date but I can say _soon_. :^)

**Comment by markpeterbuckley** [comment]
oooh, lovely! 😍  will keep our 👀  out
