### ISSUE TITLE
Configure mTLS certificate for use with CloudFoundry API

### ISSUE THREAD

**Issue by AP-Hunt** [hashicorp/vault-plugin-auth-cf#35]
Hi team,

As per #34, we're a team looking at Vault as a platform-wide secret store. 

We're planning on deploying Vault alongside the rest of our CloudFoundry components using the [community bosh release](https://github.com/cloudfoundry-community/vault-boshrelease). At the moment, this plugin allows you to [configure which certificates it's OK for the CloudFoundry API to present](https://github.com/hashicorp/vault-plugin-auth-cf/blob/master/path_config.go#L29), but not a certificate to use for mTLS when talking to CloudFoundry.

We would need this because we plan to have Vault and the CloudFoundry API communicate over an internal network where mTLS is required.

Would you be open to a PR to:
1. Add a configuration option for the mTLS cert
2. Use the mTLS certificate if the configuration option is set

Regards,
Andy

**Comment by jasonodonnell** [comment]
Hi @AP-Hunt, supporting mTLS would be a great addition.  We would be happy to review any changes to add this feature.  Let us know if this is how you want to move forward or we can plan to add it.

**Comment by AP-Hunt** [comment]
Hi Jason,

That's great news. We're still planning at the moment, but I think chances are we'd write it ourselves, contribute it, and find a way to run a version of the plugin until the changes go out in the next major release.

If we decide to go down the Vault path, we'll let you know - possibly by just raising the PRs.

**Comment by AP-Hunt** [comment]
Raised a PR to address this: https://github.com/hashicorp/vault-plugin-auth-cf/pull/41

**Comment by barsutka** [comment]
Hi team,

Just a quick check if there is an estimation when a PR #41 will be reviewed?

Thanks,
Maxim.

**Comment by jasonodonnell** [comment]
Merged #41, closing!
